kind = "web"
previewPath = "/"
title = "Mi POS"
version = "1.0.0"
id = "artifacts/mi-pos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23802

[services.development]
run = "pnpm --filter @workspace/mi-pos run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/mi-pos", "run", "build"]

[services.production.build.env]
PORT = "23802"
BASE_PATH = "/"

[services.production.run]
args = ["node", "artifacts/mi-pos/serve.mjs"]

[services.production.run.env]
PORT = "23802"
NODE_ENV = "production"

[services.env]
PORT = "23802"
BASE_PATH = "/"
